version: '3.7'

services:
  moodle: &moodle
    build: &build
      context: ./docker
      dockerfile: Dockerfile
      args:
        php: "7.0"
        version: "3.0.4"
    depends_on:
      - mysql
    ports:
      - 80:80
    tty: true
    volumes:
      - ./begateway:/var/www/html/enrol/begateway
      # - ./upload/admin/controller/extension/payment/begateway.php:/var/www/html/admin/controller/extension/payment/begateway.php
      # - ./upload/admin/language/en-gb/extension/payment/begateway.php:/var/www/html/admin/language/en-gb/extension/payment/begateway.php
      # - ./upload/admin/language/ru-ru/extension/payment/begateway.php:/var/www/html/admin/language/ru-ru/extension/payment/begateway.php
      # - ./upload/admin/view/image/payment/begateway.png:/var/www/html/admin/view/image/payment/begateway.png
      # - ./upload/admin/view/template/extension/payment/begateway.twig:/var/www/html/admin/view/template/extension/payment/begateway.twig
      # - ./upload/catalog/controller/extension/payment/begateway.php:/var/www/html/catalog/controller/extension/payment/begateway.php
      # - ./upload/catalog/language/en-gb/extension/payment/begateway.php:/var/www/html/catalog/language/en-gb/extension/payment/begateway.php
      # - ./upload/catalog/language/ru-ru/extension/payment/begateway.php:/var/www/html/catalog/language/ru-ru/extension/payment/begateway.php
      # - ./upload/catalog/model/extension/payment/begateway.php:/var/www/html/catalog/model/extension/payment/begateway.php
      # - ./upload/catalog/view/theme/default/template/extension/payment/begateway.twig:/var/www/html/catalog/view/theme/default/template/extension/payment/begateway.twig
    # restart: 

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /var/lib/mysql
      # - ./docker/etc/mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
