version: '3.7'

services:
  moodle: &moodle
    build: &build
      context: ./docker
      dockerfile: Dockerfile
      args:
        php: "8.0"
        upstream: "403"
        version: "4.3.1"
    depends_on:
      - mysql
    ports:
      - 80:80
    tty: true
    volumes:
      - ./begateway:/var/www/html/enrol/begateway

  mysql:
    image: mariadb:10.6
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
